const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVAwcEE1NG00OGpxYytFYUdqd0Q5blpVTGlBc29IVk5acWgydlhhK1lVOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiekYzd3dPL3FJaTJYVG9iL0dxN2ljRE1kZXdvZFUybWZoNnBCRnRuaGkyWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1T1h5UTRwY1FZRXpxTTFoaVp2eDJvb1RpVU5MZE9pQ3lodHVva0hkejM4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJja1NETlBkS1pJMCtxeVFXS1FYK3czaCs0dzFNcmlvOXFUbE1VWFJIU0QwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1GTWcxOW85WnNwUlV5dlU0amZmUDV3NnBhVW94K2dJaHZvM1pVL0xublE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNxMS9tbFIwSTQ1Mk1tc1FiWVZzQ25PN083VnRBend3alpIenl4ZXhibUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUNjQnZ4UWdOeHJ5c1daNGtjcmZITGhMbnBiU1FneS9iK1BJQTh2S1ZVdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidXZwUmRqZWVQTldvUGtsaWo4cnZybFkrSncyWXNaMGswZFAvU0owaEFTOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNkWFhVYmVCWnFBaVovK056OHNySTZ6K0VnWENGODdHMDJvRWtHWi96cnYxbStMMm9KT0ZlUFNvYmNZcjM3RUpJTkFHYTMyaWthcGttbGlzanhNZER3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTYwLCJhZHZTZWNyZXRLZXkiOiJMOUVvSkJESkhpSDFESG1zOFNHVWdna0FxcTYza1hMMXhaMHUzdjhMeDljPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJZVl9QQXI0MFRqT0cxazBLOEt4SHBnIiwicGhvbmVJZCI6IjMyMDU0OGUyLWM2MzUtNDhjOC04YTEyLWE5NDI2NjA3MjdmNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJSckhrREkyY1lWSm5jYVlZMW5MdENOUldYWXc9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMlAyQldMWTBTRFFFTzRWQ1BvTzU4aW5JNEtrPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkdRNjhOMzFHIiwibWUiOnsiaWQiOiIyNTQ3MTY0NDk1NTk6NjJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUGludG9vIEtpbSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTEh3N0ljRUVNekkycnNHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiL2Q2a0sySy9qb29vdzFLWU1FSkhGdWlnQkdPcE13U21uVk4zemE4aGMxbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiVlhQYWp1QWVxUFo2ZUJBdWJ3YUFhQXBINjBjWFhOYkFYaTczMWxxVVFPUitzSVNMcCtPMkVHeDN2Wi9acTFUWlJyMXVIUmdSU2RSaWNtOUZCU1VtRHc9PSIsImRldmljZVNpZ25hdHVyZSI6ImluY1dBMEJQQmR5MWd5cm4yMEw5UlQ4YkJlVlcxZjM3M3ArSFFJRnlKUTB4MVlRNnpNNWQ1TFV6OTczTXU1b2pKSWgvR3A1TEhwZkd4SUdkUEFXWUJRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzE2NDQ5NTU5OjYyQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmYzZXBDdGl2NDZLS01OU21EQkNSeGJvb0FSanFUTUVwcDFUZDgydklYTmEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU4Mjg1NjksIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSUVKIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
