const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0huOHNhdDlkckhVK1o2SWl0UE1TQW0vUWhkaHF2YU1qSms3ZUI3cGRGZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib1duYWRwb29SaFdHNXMzRjFPMU1KWTkyamhESU1uc1R2RnNDcnp2ZXJRbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5TWlKQUlBMVc1UmRYNUlmUHUydFZVdWx4b3ZQZHF3cnAvTHlJRHkyOW5VPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmck5BbDFYazFpQkZ1U29lUGdGMGhVK3pMcmhNTERUZXpMSHZMVnI1c0NNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNLdlVLbEhYQUx3NC9RVU82M0Jjb2xGTDJaRDA4QnI2ZkVkL3ErVFU4SGM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1KQTVOQU1zNmFLQUtWOU8xcVYvU242NEI4UmZIUjZlM01DNW1zRkpEaWM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0JLYlhrSjh1KzA3bDVPNUk1WkFCaUhZU3F6ZWJWVHR0WTJRTTVHZXZGRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicGZUdU1saWs5NkduOFpwd0tBZVo2eHVXc0dWQlVyemhkekdWWW54TkhUOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImV3L3F3N3NwWUI5b1FZWkRsRU1VNFJ5S1BVVXE1aXA5eERWbHc4ZzVXVlRYYkVGWm41OStOZnJRemNvM3Zhcjh5Wmd2ZkNoV20rNWZRaGh1U2Rub2lnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTc4LCJhZHZTZWNyZXRLZXkiOiJBMk1pRE94U2tTc1lLbk9WWk1kMDc4bjQwK2YyeExXd0o2ZWNodk9Fb0pNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxNjQ0OTU1OUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJEMzk5NzU3MDY4QUJDMzU5MjQ4QTU2OTBCQTkwQUI2RiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1ODMxODIyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTY0NDk1NTlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzczQkEzQUIxREIxMkI5M0NEOTgzNjFERkE5MDgxMTcifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTgzMTgyNH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoidUlKN1VGb1lRWlNmMVFYeFJfRV95QSIsInBob25lSWQiOiI4MmE4YmEwYi0yZjFjLTRmYTAtOTQ4MS1lMDU5ODIwMGFjZDgiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEs3U1pHQ3BaK3FGcXRvWmFBMTB1RlMyLzJZPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJCMmZaZGM0NUxtS1JTbkVhSlpBa0V1VE1yST0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJWOTVORTc4NSIsIm1lIjp7ImlkIjoiMjU0NzE2NDQ5NTU5OjY0QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IlBpbnRvbyBLaW0ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xIdzdJY0VFUG5oMnJzR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ii9kNmtLMksvam9vb3cxS1lNRUpIRnVpZ0JHT3BNd1NtblZOM3phOGhjMW89IiwiYWNjb3VudFNpZ25hdHVyZSI6IjI2QktNMXIva09RY3crSnl6eFM0ektUR0VDQmkyM1NzOGNDb2xNU2hPcnNqZ0trSUR3azFaODFEN2F2d1dad2RDNEdueXBWSnJqOEV2TVBrM09tRkF3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJ3cjFWZUo3QzZzbFJubUp1KytjTVNJOVI2TnJkRG9WSWtCejdJZTFLVnR2ZUZPcjl3L1B4UXgzQkwyTFNDd3M4YkNJUWdSWCtBNlNrdGNrMXdwdG9qQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDcxNjQ0OTU1OTo2NEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJmM2VwQ3RpdjQ2S0tNTlNtREJDUnhib29BUmpxVE1FcHAxVGQ4MnZJWE5hIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM1ODMxODE1LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUlFSiJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "254716449559",
  "OWNER_NAME": process.env.OWNER_NAME || "Pintoo",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
