const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOFBOUWpVM3l4eU54T09oc3pOVUt0bjhJYkFrYWVZb2pqcXdkVGxJdFgwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ3pURVN4aHpER01vdlJ2NUhLbHowUndNUzRyUlRGVk14R0M4emJRQUJTVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJR3VaemZRdGlLUmlHTkUzUCtEZWhKcTduZWMwVW5pVkg3VWRlNndGNzBvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2RG9OMXY1ZkNUTTZ1Z2RBRWxCL2VPVCtWUkZhVWxSeXdZcDVwRmxaeFVzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlCayt2QnFZN3JqcHV1bm01d1lwWFVkTE9CcmVITi9KMjV3eGVXU1lLRWM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNaV3RwOHN0T0xDelBWTzlQWDJXN0VuOFZ4TDl3TG15WENOb0NQb0FEQ0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0dkUGFoSWJUUElzS2dBQlUzNzZ4QVB5V1hSMjNZRlhpLzhYa3BWK1NFQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS01ZN3ozOXUwYVB5ZllrcXpDdzVkaFZQaUFzWEVvUTlIbWZpN2NxUmlVdz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhMaElyQ2VlRzlIaWV0SlBsSzcvOXhoRi80NERCSWtZbG5OMXZFejVGOURKTkpyUkJvWE8ra28xc2JybFlULzlSZ0FPemM5WDdBVzRCU0VVTVhRd2dRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTQsImFkdlNlY3JldEtleSI6InNJM0hqSTlPeG16d21kbGlFVmRaVUFub3pJd1ZRdGRSMXljV2d6Vk43TzA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzE2NDQ5NTU5QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjJCNzBDRTg4RTZFMjdBQjc0NzZBRDk0RDkwMDgyMEE3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU4MzI5MjB9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxNjQ0OTU1OUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1MEVGMTE3NTFGMjIxNjQ2MzZCNjg0MkYzQkUzODU5OSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1ODMyOTI0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJUSFhjWmdJc1MxcWJfLUZOTGJMZVBRIiwicGhvbmVJZCI6IjJiYzVlOWQwLTQ2NDAtNGUyMi05MWE4LWExZDE5OTk1ZDY3YiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjK05Sc1YwNXBSK2x6bm50R2IwTDJwcVlGWGs9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSDRiYjB3djVsZHd1SjNDdWdtemNwNGRpbVlJPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkZUWTQzSkVCIiwibWUiOnsiaWQiOiIyNTQ3MTY0NDk1NTk6NjZAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUGludG9vIEtpbSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTFB3N0ljRUVNTHEycnNHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiL2Q2a0sySy9qb29vdzFLWU1FSkhGdWlnQkdPcE13U21uVk4zemE4aGMxbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiU3lSQm51dnpSMmxoRlM2T0VhLzYzRDByN0xhOE5oNlZiL0Eyd21qc2VYbXFEdHppbk5aSG02UkRwNkVsYTZENDEwYzFMMS9LNDlGb0hGY29SWVA2Qnc9PSIsImRldmljZVNpZ25hdHVyZSI6Ik9YTjhSeU8ydzA1c3h5TThYUXM2dEE0UUVBR2UxdFFUYkN0SDBZVG1veURPblBjNm9EVjVMMXhRdUhmbDMxL2RhWk05MnErTlVDMzNneFk4ZGN6VGpnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzE2NDQ5NTU5OjY2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmYzZXBDdGl2NDZLS01OU21EQkNSeGJvb0FSanFUTUVwcDFUZDgydklYTmEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU4MzI5MTIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSi9HIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "254716449559",
  "OWNER_NAME": process.env.OWNER_NAME || "Pintoo",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
